name: Linux Cloud VPS

on:
  workflow_dispatch:
  schedule:
    # اجرای خودکار هر ۵ ساعت و ۴۵ دقیقه
    - cron: '45 */5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install and Setup Tailscale
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        # دانلود و نصب Tailscale
        curl -fsSL https://tailscale.com/install.sh | sh
        
        # اتصال به شبکه Tailscale
        sudo tailscale up --authkey="$TAILSCALE_AUTHKEY" --hostname="github-ubuntu-server"
        
        # تنظیم رمز عبور یوزر runner
        echo "runner:$SERVER_PASSWORD" | sudo chpasswd
        
        # فعال‌سازی دسترسی SSH با رمز عبور
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        sudo service ssh restart
        
        echo "=========================================="
        echo "Server successfully started on Tailscale!"
        echo "=========================================="

    - name: Keep Alive (6 Hours)
      run: |
        for i in {1..360}; do
          sleep 60
        done
